eos-update-flatpak-repos: fix migrating non-extra data apps
fa409368c1ffbce4be40a3b79f449b71f9ae072d added support for migrating
extra data apps, but broke migrating normal apps:

    Failure applying migration to com.github.Slingshot
    Traceback (most recent call last):
      File "/usr/sbin/eos-update-flatpak-repos", line 1495, in _migrate_installed_flatpaks
        **kwargs,
      File "/usr/sbin/eos-update-flatpak-repos", line 1331, in copy_commit
        metadata, vendor_prefixes = rewrite_app_id(repo, mtree, old_app_id, new_app_id)
      File "/usr/sbin/eos-update-flatpak-repos", line 1235, in rewrite_app_id
        if metadata.remove_group(FLATPAK_METADATA_GROUP_EXTRA_DATA):
    GLib.GError: g-key-file-error-quark: Key file does not have group “Extra Data” (4)

This is because g_key_file_remove_group() returns FALSE with the GError
set if the group is not present; this becomes an exception in Python.

https://phabricator.endlessm.com/T23856
(cherry picked from commit c3c7996392fcd8e9bff327bd8b662fa9c4bf2423)