eos-preset: Disable systemd-sysupdate.timer & systemd-sysupdate-reboot.timer
The process systemd-sysupdate brought by systemd-sysupdate.service is
failed. Because, EOS does not have directories: /etc/sysupdate.*.d/,
/run/sysupdate.*.d/, nor /usr/lib/sysupdate.*.d/.

systemd-sysupdate.service - Automatic System Update
     Loaded: loaded (/lib/systemd/system/systemd-sysupdate.service; indirect; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-04-03 11:49:02 CST; 8min ago
   Duration: 67ms
TriggeredBy: ● systemd-sysupdate.timer
       Docs: man:systemd-sysupdate.service(8)
    Process: 3400 ExecStart=/lib/systemd/systemd-sysupdate update (code=exited, status=1/FAILURE)
   Main PID: 3400 (code=exited, status=1/FAILURE)
      Error: 2 (No such file or directory)
        CPU: 24ms

Apr 03 11:49:02 endless systemd[1]: Started systemd-sysupdate.service - Automatic System Update.
Apr 03 11:49:02 endless systemd-sysupdate[3400]: No transfer definitions found.
Apr 03 11:49:02 endless systemd[1]: systemd-sysupdate.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 11:49:02 endless systemd[1]: systemd-sysupdate.service: Failed with result 'exit-code'.

Besides, EOS uses the filesystem maintained by OSTree. The debian
packages will not be updated with apt, nor dpkg in normal case. So,
disable systemd-sysupdate.timer to avoid triggering
systemd-sysupdate.service automatically. And,
systemd-sysupdate-reboot.timer hits the same issue.

https://phabricator.endlessm.com/T35292